### ISSUE TITLE
Showing fields marks them as dirty for update/save operation

### ISSUE THREAD

**Issue by Nafferty** [gotdibbs/Dynamics-CRM-Bookmarklets#37]
## What is the current behavior? How do you reproduce it?
Currently using the Chrome extension, version 2.2.2. By using "Show All Fields" command on a form, all fields get marked dirty as well. Saving the form after showing all fields erroneously triggers plugins and flows that have filter criteria different than the fields that are actually changed.

## What is the expected behavior?
Clicking "Show All Fields" should not set fields to dirty if they are not changed. Perhaps before setting the field visibility, the dirty-ness of the field can be tracked and set accordingly after the visibility change.

## Please tell us about your environment:**
Chrome, using the 2.2.2 version of the Toolbox. Latest version of Dynamics (2020 Release wave 1; 9.1.0000.2251).

## Other information
End-user here complained about this problem describing it as such: they have a flow that triggers on a field that is not visible by default. They used Show All Fields, updated a _different_ field, and then hit save. The flow was still triggered although the field that's supposed to trigger it was not actually changed. Unfortunately, flows still do not have support for pre/post-image type comparisons, so it's not possible to just add a condition to the flow to check before/after for non-updates.

**Comment by Nafferty** [comment]
From the user: "and just another observation...if you use the dirty fields functionality in the toolbox it will only show you the one(s) you updated as dirty, but in the background it's really sending all fields on the form as described above"

**Comment by gotdibbs** [comment]
Thanks so much for the detailed report! Super helpful.

I'm guessing this is the `Unlock All Fields` feature? If so, it's probably the [`setSubmitMode` call here](https://github.com/gotdibbs/Dynamics-365-Toolkit/blob/8c0195458f346990982b4643439dc65d0c7c9f8b/chromeExtension/src/utilities/enable-all-fields.js#L14) that is doing it.

I'm guessing instead of `always` it should be set to `dirty`, but if you could help confirm that, I can definitely patch it up and push a new version!

Edit: if they really mean the `Show All Fields` feature, then I'm not sure where that behavior would be coming from because [there's no `setSubmitMode` call](https://github.com/gotdibbs/Dynamics-365-Toolkit/blob/master/chromeExtension/src/utilities/show-all-fields.js), but I can dig.

**Comment by gotdibbs** [comment]
Assuming I was right, this should be fixed in #38 (v2.2.3) for v9+.

**Comment by Nafferty** [comment]
The person who originally submitted this to me confirmed that the update you pushed fixed their issue. Thanks Dibbs!! You are way too good to us with that super fast turnaround.
